"""Single-source problem definitions for the benchmark corpus.

A problem is written once as SymPy expressions over symbols named ``x(1)``,
``x(2)``, ... (that spelling is what MATLAB needs; NumPy callables are made
with ``lambdify(dummify=True)``).  From the same expressions we derive exact
gradients, Jacobians and the Hessian of the Lagrangian for the oracle, and we
emit MATLAB code with SymPy's Octave/MATLAB printer.  Nothing is translated by
hand, so a cross-language discrepancy is a generator bug, not a transcription
slip.

Canonical form:  min f(x)  s.t.  cl <= c(x) <= cu,  xl <= x <= xu.
Row kinds are derived from the bounds exactly: ``cl == cu`` is an equality;
``-inf < cl < cu < inf`` is ranged; otherwise one-sided.  No ``isclose``.
"""
from __future__ import annotations

import hashlib
import json
import math
from dataclasses import dataclass, field
from typing import Callable

import numpy as np
import sympy as sp

from codegen import make_fn, ml_assign, ml_expr

INF = float("inf")


def xs(n: int) -> list[sp.Symbol]:
    """Symbols x_1 .. x_n (codegen maps them to x[0..] in NumPy and x(1..) in MATLAB)."""
    return [sp.Symbol(f"x_{i + 1}", real=True) for i in range(n)]


@dataclass
class Spec:
    """One benchmark instance."""

    name: str
    family: str
    x: list[sp.Symbol]
    f: sp.Expr
    c: list[sp.Expr]
    cl: list[float]
    cu: list[float]
    xl: list[float]
    xu: list[float]
    x0: list[float]
    ref_f: float | None = None          # published or closed-form optimum (documented in `source`)
    ref_x: list[list[float]] | None = None  # known minimizer(s), if any
    source: str = ""
    tags: list[str] = field(default_factory=list)
    notes: str = ""

    # ---- derived ----
    @property
    def n(self) -> int:
        return len(self.x)

    @property
    def m(self) -> int:
        return len(self.c)

    def row_kinds(self) -> list[str]:
        kinds = []
        for lo, hi in zip(self.cl, self.cu):
            if lo == hi:
                kinds.append("eq")
            elif math.isfinite(lo) and math.isfinite(hi):
                kinds.append("ranged")
            elif math.isfinite(lo):
                kinds.append("lower")
            elif math.isfinite(hi):
                kinds.append("upper")
            else:
                kinds.append("free")
        return kinds

    def validate(self) -> None:
        n, m = self.n, self.m
        assert len(self.xl) == n and len(self.xu) == n and len(self.x0) == n, self.name
        assert len(self.cl) == m and len(self.cu) == m, self.name
        for lo, hi in zip(self.xl, self.xu):
            assert lo <= hi and not math.isnan(lo) and not math.isnan(hi), self.name
        for lo, hi in zip(self.cl, self.cu):
            assert lo <= hi and not (math.isinf(lo) and math.isinf(hi) and lo == hi), self.name
        free = [s for e in [self.f, *self.c] for s in e.free_symbols if s not in self.x]
        assert not free, f"{self.name}: unknown symbols {free}"

    def checksum(self) -> str:
        h = hashlib.sha256()
        h.update(str(self.f).encode())
        for e in self.c:
            h.update(str(e).encode())
        h.update(json.dumps([self.cl, self.cu, self.xl, self.xu, self.x0], default=_num).encode())
        return h.hexdigest()[:16]

    def manifest_row(self, split: str | None = None) -> dict:
        kinds = self.row_kinds()
        return dict(
            name=self.name, family=self.family, n=self.n, m=self.m,
            n_eq=kinds.count("eq"), n_ranged=kinds.count("ranged"),
            n_bounded=sum(1 for lo, hi in zip(self.xl, self.xu) if math.isfinite(lo) or math.isfinite(hi)),
            n_fixed=sum(1 for lo, hi in zip(self.xl, self.xu) if lo == hi),
            linear_rows=sum(1 for e in self.c if _is_linear(e, self.x)),
            ref_f=self.ref_f, has_ref_x=self.ref_x is not None, source=self.source,
            tags=list(self.tags), checksum=self.checksum(), split=split,
        )

    # ---- NumPy callables (exact derivatives) ----
    def numpy(self) -> "NumpyProblem":
        return NumpyProblem(self)

    # ---- MATLAB code ----
    def matlab(self) -> str:
        n, m = self.n, self.m
        lines = [f"function p = {self.name}()",
                 f"% {self.name}: generated by bench/corpus/generate.py from the SymPy definition. Do not edit.",
                 f"% source: {self.source}",
                 f"p.name = '{self.name}'; p.family = '{self.family}'; p.n = {n}; p.m = {m};",
                 f"p.x0 = {_mvec(self.x0)};",
                 f"p.xl = {_mvec(self.xl)}; p.xu = {_mvec(self.xu)};",
                 f"p.cl = {_mvec(self.cl)}; p.cu = {_mvec(self.cu)};",
                 f"p.ref_f = {_mnum(self.ref_f) if self.ref_f is not None else 'NaN'};",
                 f"p.checksum = '{self.checksum()}';",
                 f"p.f = @{self.name}_f; p.grad = @{self.name}_g; p.c = @{self.name}_c; p.jac = @{self.name}_J;",
                 "end", "",
                 f"function f = {self.name}_f(x)", *ml_assign("f", self.f), "end", "",
                 f"function g = {self.name}_g(x)", f"g = zeros({n}, 1);"]
        idx = {v: j for j, v in enumerate(self.x)}
        gd = sparse_grad(self.f, idx)
        for j in sorted(gd):
            lines += ml_assign(f"g({j + 1})", gd[j])
        lines += ["end", "", f"function c = {self.name}_c(x)", f"c = zeros({m}, 1);"]
        for i, e in enumerate(self.c):
            lines += ml_assign(f"c({i + 1})", e)
        lines += ["end", "", f"function J = {self.name}_J(x)", f"J = zeros({m}, {n});"]
        for i, e in enumerate(self.c):
            gd = sparse_grad(e, idx)
            for j in sorted(gd):
                lines += ml_assign(f"J({i + 1}, {j + 1})", gd[j])
        lines += ["end", ""]
        return "\n".join(lines)


class NumpyProblem:
    """Callables with exact derivatives, derived from a Spec (sparsity-aware: only
    structurally nonzero derivative entries are generated)."""

    def __init__(self, s: Spec):
        self.spec = s
        self.name, self.family, self.n, self.m = s.name, s.family, s.n, s.m
        self.x0 = np.asarray(s.x0, float)
        self.xl, self.xu = np.asarray(s.xl, float), np.asarray(s.xu, float)
        self.cl, self.cu = np.asarray(s.cl, float), np.asarray(s.cu, float)
        self.ref_f, self.ref_x = s.ref_f, s.ref_x
        self.row_kinds = s.row_kinds()
        idx = {v: j for j, v in enumerate(s.x)}
        self._f = make_fn([s.f])
        gd = sparse_grad(s.f, idx)
        gcols = sorted(gd)
        self._gcols = np.asarray(gcols, dtype=int)
        self._g = make_fn([gd[j] for j in gcols])
        if s.m:
            self._c = make_fn(list(s.c))
            rows, cols, exprs = [], [], []
            for i, e in enumerate(s.c):
                gd = sparse_grad(e, idx)
                for j in sorted(gd):
                    rows.append(i); cols.append(j); exprs.append(gd[j])
            self.jac_rows, self.jac_cols = np.asarray(rows, int), np.asarray(cols, int)
            self._J = make_fn(exprs)
        else:
            self.jac_rows = self.jac_cols = np.zeros(0, int)
        self._H = None

    def f(self, x) -> float:
        return float(self._f(np.asarray(x, float))[0])

    def grad(self, x) -> np.ndarray:
        g = np.zeros(self.n)
        if self._gcols.size:
            g[self._gcols] = self._g(np.asarray(x, float))
        return g

    def cons(self, x) -> np.ndarray:
        if not self.m:
            return np.zeros(0)
        return self._c(np.asarray(x, float))

    def jac_values(self, x) -> np.ndarray:
        """Values of the structurally nonzero Jacobian entries (rows/cols in jac_rows/jac_cols)."""
        if not self.jac_rows.size:
            return np.zeros(0)
        return self._J(np.asarray(x, float))

    def jac(self, x) -> np.ndarray:
        J = np.zeros((self.m, self.n))
        if self.jac_rows.size:
            J[self.jac_rows, self.jac_cols] = self.jac_values(x)
        return J

    def hess_lagrangian(self, x, lam) -> np.ndarray:
        """Hessian of f + lam^T c (stationarity is grad f + J^T lam - zl + zu = 0)."""
        if self._H is None:
            s = self.spec
            idx = {v: j for j, v in enumerate(s.x)}
            lsym = [sp.Symbol(f"lam{i}") for i in range(s.m)]
            L = s.f + sum(l * e for l, e in zip(lsym, s.c))
            rows, cols, exprs = [], [], []
            g1 = sparse_grad(L, idx)
            for ja in sorted(g1):
                g2 = sparse_grad(g1[ja], idx)
                for jb in sorted(g2):
                    if jb >= ja:
                        rows.append(ja); cols.append(jb); exprs.append(g2[jb])
            self._Hrc = (np.asarray(rows, int), np.asarray(cols, int))
            self._H = make_fn(exprs, lam_syms=lsym)
        H = np.zeros((self.n, self.n))
        r, c = self._Hrc
        if r.size:
            vals = self._H(np.asarray(x, float), np.asarray(lam, float))
            H[r, c] = vals
            off = r != c
            H[c[off], r[off]] = vals[off]
        return H

    def violation(self, x) -> float:
        """Independent maximum violation of bounds and constraint rows (0 when feasible)."""
        x = np.asarray(x, float)
        v = 0.0
        fin = np.isfinite(self.xl)
        if fin.any():
            v = max(v, float(np.max(self.xl[fin] - x[fin])))
        fin = np.isfinite(self.xu)
        if fin.any():
            v = max(v, float(np.max(x[fin] - self.xu[fin])))
        if self.m:
            c = self.cons(x)
            fin = np.isfinite(self.cl)
            if fin.any():
                v = max(v, float(np.max(self.cl[fin] - c[fin])))
            fin = np.isfinite(self.cu)
            if fin.any():
                v = max(v, float(np.max(c[fin] - self.cu[fin])))
        return max(v, 0.0)

    def probes(self, k: int = 4) -> list[np.ndarray]:
        """Deterministic probe points inside the box for cross-language equivalence checks."""
        out = [self.x0.copy()]
        rng = np.random.default_rng(int(self.spec.checksum(), 16) % (2**32))
        for _ in range(k):
            step = rng.uniform(-0.3, 0.3, self.n) * np.maximum(1.0, np.abs(self.x0))
            x = self.x0 + step
            lo = np.where(np.isfinite(self.xl), self.xl, -np.inf)
            hi = np.where(np.isfinite(self.xu), self.xu, np.inf)
            out.append(np.clip(x, lo, hi))
        return out


# ---------------- registry ----------------
_REGISTRY: dict[str, Callable[[], Spec]] = {}


def register(fn: Callable[[], Spec]) -> Callable[[], Spec]:
    """Decorator: register a zero-argument Spec factory under the function's name
    (which must equal the Spec name; checked lazily by `get`)."""
    assert fn.__name__ not in _REGISTRY, f"duplicate problem {fn.__name__}"
    _REGISTRY[fn.__name__] = fn
    return fn


def names() -> list[str]:
    return sorted(_REGISTRY)


def get(name: str) -> Spec:
    s = _REGISTRY[name]()
    assert s.name == name, f"factory {name} produced Spec named {s.name}"
    s.validate()
    return s


def all_specs() -> list[Spec]:
    return [get(n) for n in names()]


# ---------------- helpers ----------------
def sparse_grad(e: sp.Expr, idx: dict) -> dict:
    """{column: derivative} for the symbols in `idx` that `e` depends on, differentiating
    term by term so a 1000-term separable sum costs O(terms), not O(terms * n)."""
    terms = e.args if isinstance(e, sp.Add) else (e,)
    acc: dict = {}
    for t in terms:
        for v in t.free_symbols:
            j = idx.get(v)
            if j is None:
                continue
            d = sp.diff(t, v)
            if d != 0:
                acc.setdefault(j, []).append(d)
    return {j: (ds[0] if len(ds) == 1 else sp.Add(*ds)) for j, ds in acc.items()}

def _num(v):
    if isinstance(v, float) and math.isinf(v):
        return "inf" if v > 0 else "-inf"
    return v


def _mnum(v: float) -> str:
    if math.isinf(v):
        return "Inf" if v > 0 else "-Inf"
    return repr(float(v))


def _mvec(v: list[float]) -> str:
    if not v:
        return "zeros(0, 1)"
    return "[" + "; ".join(_mnum(float(t)) for t in v) + "]"


def _is_linear(e: sp.Expr, x: list[sp.Symbol]) -> bool:
    """Linear iff every first derivative is free of the variables (cheap, no polynomial construction)."""
    idx = {v: j for j, v in enumerate(x)}
    xset = set(x)
    for d in sparse_grad(e, idx).values():
        if d.free_symbols & xset:
            return False
    return True
