[package]
name = "mincon-ip"
description = "Primal-dual interior-point method with a filter line search for mincon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
mincon-core.workspace = true
mincon-linalg.workspace = true
mincon-diff.workspace = true

[dev-dependencies]
mincon-testset.workspace = true

[lints]
workspace = true
